name: Exploring Github Enterprise Action Features/Policies

on:
    workflow_dispatch: 
    push:

jobs:
  demo_job:
    runs-on: self-hosted
    steps:
      - name: Hello
        run: |
          echo "Hello Github Enterprise!!"

      - name: External Call using cURL
        run: curl -v http://httpbin.org/ip

      - name: External call with INVALID Proxy credentials
        run: curl -v -x http://kk-proxy-user-123:kk-proxy-password-123@localhost:3128 http://httpbin.org/ip